### PR TITLE
Fix incorrect dependency attributes assignment

### LINKED ISSUE #2: Incorrect dependency attributes assignment
Attributes are not correctly assigned on dependency on lines like that:
'gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]'

I already have created corresponding change, if you give me access rights, I'll create patch myself. If not, here, file with fix, branched from master:
https://pastebin.com/Eu9QgnKR
Please, add this fix to correctly parse dependencies from manifests like this one:
https://github.com/rails/rails/blob/master/Gemfile

### PR DESCRIPTION
**Pull request by uvarenkovserf**
Fixes: #2

### CODE REVIEW

**Comment by balasankarc** [comment]
@uvarenkovserf Unfortunately, this is not an easy fix. Your solution actually just ignores an attribute if some other value has been already set on it. For example, see the following

```python
In [1]: cat Gemfile
gem 'byebug', platforms: [:mri, :mingw, :x64_mingw], group: development

In [2]: from gemfileparser import GemfileParser

In [3]: parser = GemfileParser('Gemfile')

In [4]: result = parser.parse()

In [5]: result
Out[5]: 
{'development': [],
 'metrics': [],
 'production': [],
 'runtime': [<gemfileparser.Dependency at 0x7f7e729ea190>],
 'test': []}
```

The group is incorrectly identified as `runtime` while it was specified to be `development`.

Unfortunately this is not an easy problem to fix. Because we are using `csv.reader` and the commas inside `platforms` field will mess everything up. To be honest, I never knew multiple platforms could be specified using a list format. 

A possible solution is to check of such multi-values fields and convert them to something other than comma separated before the check happens and convert them back after the check. I will try to take a look at it this weekend. 

As a general suggestion, we should never ignore an attribute, but find a way to recognize it and return it to the user.

**Comment by balasankarc** [comment]
@uvarenkovserf I've started making the code relatively better in the [dev branch](https://github.com/balasankarc/gemfileparser/tree/dev). Any testing would be a great help.

**Comment by pombredanne** [comment]
>  Because we are using csv.reader and the commas inside platforms field will mess everything up. To be honest, I never knew multiple platforms could be specified using a list format.

FWIW, a better option may be to look at the `shlex` module
But is this still an existing issue in the latest code? @uvarenkovserf I know this has been a while since you provided this patch.. but could you test with the latest develop? @rpotter12 ^

**Comment by pombredanne** [comment]
@uvarenkovserf i am closing for now. Feel free to reopen

**Pull request closed without merging**
